# Generated by Django 4.2.7 on 2023-11-08 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='email',
            new_name='EMAIL',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='name',
            new_name='NAME',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='password',
            new_name='PASSW',
        ),
    ]
